# Generated by Django 3.0.6 on 2020-06-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageCode',
        ),
    ]
