# Generated by Django 3.0.6 on 2020-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecode',
            name='language_code',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
