# Generated by Django 3.0.6 on 2020-06-09 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_auto_20200531_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='level',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
