# Generated by Django 3.0.7 on 2020-07-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Der'), ('F', 'Die'), ('N', 'Das')], max_length=1)),
                ('second_gender', models.CharField(blank=True, choices=[('M', 'Der'), ('F', 'Die'), ('N', 'Das')], default='', max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lesson.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5)),
                ('order', models.SmallIntegerField(default=0)),
                ('term', models.CharField(blank=True, max_length=32)),
                ('meaning', models.CharField(max_length=192)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='card.Card')),
            ],
        ),
    ]
