# Generated by Django 3.0.7 on 2020-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='second_gender',
            field=models.CharField(choices=[('M', 'Der'), ('F', 'Die'), ('N', 'Das')], default=None, max_length=1, null=True),
        ),
    ]
