# Generated by Django 3.0.7 on 2020-07-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_second_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='second_gender',
            field=models.CharField(blank=True, choices=[('M', 'Der'), ('F', 'Die'), ('N', 'Das')], default='', max_length=1),
        ),
    ]
