# Generated by Django 3.0.6 on 2020-05-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200523_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='card',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='user',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
    ]
