# Generated by Django 3.0.6 on 2020-05-31 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200525_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5)),
                ('term', models.CharField(blank=True, max_length=32)),
                ('meaning', models.CharField(max_length=192)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='main.Card')),
            ],
        ),
    ]
