# Generated by Django 3.0.7 on 2020-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
