# Generated by Django 3.0.6 on 2020-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_meaning_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meaning',
            name='is_main',
        ),
        migrations.AddField(
            model_name='meaning',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
